controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
auth:
    path: /auth
<<<<<<< HEAD
    methods: ['POST']
=======
    methods: ['POST']
>>>>>>> master
