<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBoy3wSH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBoy3wSH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBoy3wSH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBoy3wSH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBoy3wSH\App_KernelDevDebugContainer([
    'container.build_hash' => 'Boy3wSH',
    'container.build_id' => '4dc6478e',
    'container.build_time' => 1712651423,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBoy3wSH');
